fixed the drawer behaviour and also added the ability to search work Cell and Equiqment
barbinbrad/carbon pull request #68
Opened 2024-02-25 22:03 UTC by alidauda

### **FIx**
-        Fix issue with Color component closing Drawer prematurely

### **Added functionality**  
**Ability to search Work cell and Equiqument**

- I encountered an issue where newly created entities weren't appearing in the search tab upon addition. To address this, I chose to utilize the pre-existing 'Part' entity instead of creating a new one. The item is visible in the search table when I inspect the database directly. However, when I attempt to search using the search UI, it does not appear in the results.

2024-02-27 04:37 UTC, barbinbrad requested changes
Good work. A couple fixes to make, but very strong start.

2024-02-27 04:37 UTC, barbinbrad commented on packages/database/supabase/migrations/20240223235518_add_search_functionality_to_equipment_and_work_cell_types.sql
> +    WHERE entity = 'Part' AND uuid = new.id;
```suggestion
    WHERE entity = 'Resource' AND uuid = new.id;
```

2024-02-27 04:37 UTC, barbinbrad commented on packages/database/supabase/migrations/20240223235518_add_search_functionality_to_equipment_and_work_cell_types.sql
> +  VALUES (new.id, new.id || ' ' || new.name || ' ' || COALESCE(new.description, ''), 'Part', new.id, '/x/resources/equipment/' || new.id);
Same thing here. Let's use name instead of id for the result.
```suggestion
  VALUES (new.name, COALESCE(new.description, ''), 'Resource', new.id, '/x/resources/equipment/' || new.id);
```

2024-02-27 04:37 UTC, barbinbrad commented on packages/database/supabase/migrations/20240223235518_add_search_functionality_to_equipment_and_work_cell_types.sql
> +  DELETE FROM public.search WHERE entity = 'Part' AND uuid = old.id;
```suggestion
  DELETE FROM public.search WHERE entity = 'Resource' AND uuid = old.id;
```

2024-02-27 04:37 UTC, barbinbrad commented on packages/database/supabase/migrations/20240223235518_add_search_functionality_to_equipment_and_work_cell_types.sql
> +  VALUES (new.id, new.id || ' ' || new.name || ' ' || COALESCE(new.description, ''), 'Part', new.id, '/x/resources/work-cells/' || new.id);
The name is what's returned in the search result. Let's use the name for the name (instead of the id).

![Screenshot 2024-02-26 at 10 33 08 PM](https://github.com/barbinbrad/carbon/assets/64510427/fdc5f12c-9c4b-429f-8fad-912f00046d5a)


```suggestion
  VALUES (new.name, COALESCE(new.description, ''), 'Resource', new.id, '/x/resources/work-cells/' || new.id);
```

2024-02-27 04:37 UTC, barbinbrad commented on packages/database/supabase/migrations/20240223235518_add_search_functionality_to_equipment_and_work_cell_types.sql
> +    WHERE entity = 'Part' AND uuid = new.id;
```suggestion
    WHERE entity = 'Resource' AND uuid = new.id;
```

2024-02-27 04:37 UTC, barbinbrad commented on packages/database/supabase/migrations/20240223235518_add_search_functionality_to_equipment_and_work_cell_types.sql
> +  DELETE FROM public.search WHERE entity = 'Part' AND uuid = old.id;
```suggestion
  DELETE FROM public.search WHERE entity = 'Resource' AND uuid = old.id;
```

2024-02-27 04:37 UTC, barbinbrad commented on apps/carbon/app/components/Form/Color.tsx
> +            }}
I agree that something is not right here, but this prevents the form from being submitted with the enter key. Please revert this change.

2024-02-27 04:37 UTC, barbinbrad commented on packages/database/supabase/migrations/20240223235518_add_search_functionality_to_equipment_and_work_cell_types.sql
> +    UPDATE public.search SET name = new.name, description = new.id || ' ' || new.name || ' ' || COALESCE(new.description, '')
```suggestion
    UPDATE public.search SET name = new.name, description = COALESCE(new.description, '')
```

2024-02-27 04:37 UTC, barbinbrad commented on packages/database/supabase/migrations/20240223235518_add_search_functionality_to_equipment_and_work_cell_types.sql
> +    UPDATE public.search SET name = new.name, description = new.id || ' ' || new.name || ' ' || COALESCE(new.description, '')
```suggestion
    UPDATE public.search SET name = new.name, description = COALESCE(new.description, '')
```

2024-02-27 20:50 UTC, barbinbrad commented on apps/carbon/app/components/Form/Color.tsx
>            <button
```suggestion
          <button
            type="button"
```

This is a suggestion from @sapter -- basically any button in a form that does not have a type specified will default to a submit, if I understand correctly.

2024-02-29 22:35 UTC, alidauda commented
Ability to search Work cell and Equiqument

2024-02-29 23:22 UTC, merged